In [2]:
import numpy as np
a= np.array([1,2,3,5])
b= np.array([4,6,7,8])
c= np.concatenate((a,b))
c

array([1, 2, 3, 5, 4, 6, 7, 8])

In [5]:
a= np.array([1,2]),([3,4])
b= np.array([5,6]),([7,8])
#print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
a= np.array([1,2,3])
print(np.tile(a,2))

[1 2 3 1 2 3]


In [7]:
print(np.repeat(a,2))

[1 1 2 2 3 3]


In [8]:
print(np.sum(a))

6


In [9]:
print(np.mean(a))

2.0


In [10]:
print(np.median(a))

2.0


In [11]:
print(np.max(a))

3


In [12]:
print(np.min(a))

1


In [13]:
#where
a

array([1, 2, 3])

In [14]:
res= np.where(a<3,"low","high")
res

array(['low', 'low', 'high'], dtype='<U4')

In [15]:
arr=np.array([[1,3,2],[4,5,6]])
arr

array([[1, 3, 2],
       [4, 5, 6]])

In [16]:
print(np.argwhere(arr>2))

[[0 1]
 [1 0]
 [1 1]
 [1 2]]


In [17]:
a

array([1, 2, 3])

In [18]:
d=np.logical_and(a>1,a<3)
d

array([False,  True, False])

In [20]:
print(a[d])

[2]


In [21]:
b=([4,5,6])
b

[4, 5, 6]

In [22]:
d=np.logical_or(a>1,a<3)
d

array([ True,  True,  True])

In [25]:
arr=np.array([0,2,3,4,5])
arr

array([0, 2, 3, 4, 5])

In [26]:
print(np.nonzero(arr))

(array([1, 2, 3, 4], dtype=int64),)


In [27]:
#boradcasting
arr=np.array([[10,20],[30,40]])
arr.shape

(2, 2)

In [28]:
res=arr+100
res

array([[110, 120],
       [130, 140]])

In [29]:
#vectorization to convert normal array this is a user define function
def cube(x):
    return x*x*x
ourfun =np.vectorize(cube)

In [30]:
a

array([1, 2, 3])

In [31]:
print(ourfun(a))

[ 1  8 27]


In [32]:
def squre(x):
    return x*x
ourfun =np.vectorize(squre)
print(ourfun(a))

[1 4 9]
